version: '3.8'

services:
  server: &app
    build: .
    ports:
      - 2300:2300
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true

  check_daemon:
    <<: *app
    cap_add:
      - NET_RAW
    ports: []
    command: bin/check_daemon -t 60 run
    tty: true
    stdin_open: true

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=monitoring
    ports:
      - 5432:5432
    volumes:
      - ./persistence/postgres/:/var/lib/postgresql/data:delegated
