version: '3.8'

services:
  server: &app
    build: .
    ports:
      - 2300:2300
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  check_daemon:
    <<: *app
    ports: []
    depends_on:
      - server
    command: bin/check_daemon -t 60 run

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=monitoring
    ports:
      - 5432:5432
    volumes:
      - ./persistence/postgres/:/var/lib/postgresql/data:delegated
