name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: hanami_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      HANAMI_ENV: test
      DATABASE_URL: postgres://postgres:password@localhost:5432/hanami_test
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Prepare database
        run: |
          bundle exec hanami db create
          bundle exec hanami db migrate

      - name: Run tests
        run: |
          bundle exec rspec
