name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test with RSpec and RuboCop
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: monitoring_test
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get -yqq install libpq-dev

      - name: Setup database
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/monitoring_test"
          HANAMI_ENV: "test"
        run: |
          bundle exec hanami db create
          bundle exec hanami db migrate

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/monitoring_test"
          HANAMI_ENV: "test"
        run: bundle exec rspec